-- bootstrap lazy.nvim, LazyVim and your plugins
-- Suppress the initial colorscheme error during startup
local original_notify = vim.notify
vim.notify = function(msg, log_level, _opts)
  if msg and type(msg) == "string" and msg:match("Cannot find color scheme") then 
    return 
  end
  original_notify(msg, log_level, _opts)
end


require("config.lazy")
-- This loads the filled-in color file generated by Noctalia
pcall(function()
  require("matugen").setup()
end)
