return {
  {
    'RRethy/base16-nvim',
    lazy = false, -- Load immediately
    priority = 1000, -- Highest priority
    config = function()
      -- Try to load the Matugen file generated by Noctalia
      local status, matugen = pcall(require, "matugen")
      if status then
          matugen.setup()
      else
          -- Fallback if the file isn't generated yet
          require('base16-colorscheme').setup(require('base16-colorscheme').colorschemes.classic)
      end
    end,
  }
}
